name: Push master to repo

on:
  push:
    branches:
      - 'master'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TEST }}
          ref: 'master'
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add remote
        run: |
          git remote add target https://x-access-token:${{ secrets.TEST }}@github.com/Nats92/test2.git || echo "Remote already exists"
          git fetch target

      - name: Push master
        run: |
          git push target master:master
